name: music
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  just_audio: ^0.9.30
  audio_session: ^0.1.11
  video_player: ^2.4.8
  chewie: ^1.3.6

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/images/icons8'
  color_dark: '#262626'
  image_dark: 'assets/images/icons8'
  fullscreen: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/